<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Error.proto

namespace GPBMetadata;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a450a0b4572726f722e70726f746f12034c696222290a08527063457272" .
            "6f72120c0a04636f6465180120012805120f0a076d657373616765180220" .
            "012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

