<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: User.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad9010a0a557365722e70726f746f12084c69622e5573657222320a0c4c" .
            "6f67696e5265717565737412100a08757365726e616d6518012001280912" .
            "100a0870617373776f7264180220012809223c0a0d4c6f67696e52657370" .
            "6f6e7365120a0a02696418012001280d12100a08757365726e616d651802" .
            "20012809120d0a05746f6b656e18032001280932470a0b55736572536572" .
            "7669636512380a054c6f67696e12162e4c69622e557365722e4c6f67696e" .
            "526571756573741a172e4c69622e557365722e4c6f67696e526573706f6e" .
            "7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

